# -*- coding: utf-8 -*-


import random

from code.datamodel.Category import Category
from code.datamodel.Content import Content


__author__ = 'mjjaniec'


class ContentGenerator(object):
    def generate_content(self):
        return random.choice(self.contents)

    @staticmethod
    def _generate_categories(hint):
        interests = []
        sum = 0.0
        hint_space = 0.5 + random.random() / 2
        rest_space = 1.0 - hint_space
        for i in xrange(random.randint(0, 3)):
            val = random.expovariate(1)
            interests.append(val)
            sum += val
        interests = map(lambda x: rest_space * x / sum, interests)

        result = {hint: hint_space}
        if len(interests) > 0:
            for val in interests:
                category = None
                while True:
                    category = random.choice(Category)
                    if not category in result:
                        break
                result[category] = val
        else:
            result[hint] = 1.0
        return result

    def __init__(self):
        self.contents = [
            Content(""" Muse - Greatest Hits (2012) Full Album """, 0.591944787009,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse - Madness """, 0.769186601583, ContentGenerator._generate_categories("music")),
            Content(""" muse """, 0.188081359228, ContentGenerator._generate_categories("music")),
            Content(""" Muse - The 2nd Law (Full Album) """, 0.548707612686,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse - Uprising """, 0.776071250433, ContentGenerator._generate_categories("music")),
            Content(""" Muse - Live at iTunes Festival 2012 (Full HD 1080p) """, 0.638099768796,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse - Supremacy (Official Video) """, 0.690957924091,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse - Resistance """, 0.751213854425, ContentGenerator._generate_categories("music")),
            Content(""" Live At Rome Olympic Stadium FULL HD """, 0.553555234085,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse - Hysteria """, 0.722403669408, ContentGenerator._generate_categories("music")),
            Content(""" Muse - Feeling Good (Video) """, 0.726683721633,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse - Knights Of Cydonia  (Video) """, 0.685996824963,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse - Undisclosed Desires """, 0.749687122185, ContentGenerator._generate_categories("music")),
            Content(""" Muse - Austin City Limits 2013 (Full) (HD) """, 0.549372008224,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse - Bliss """, 0.704095216618, ContentGenerator._generate_categories("music")),
            Content(""" Muse - Follow Me """, 0.676271149085, ContentGenerator._generate_categories("music")),
            Content(""" Muse - Starlight (Video) """, 0.747597819425, ContentGenerator._generate_categories("music")),
            Content(""" Muse- Coachella Music & Arts Festival 2014 Weekend One [PROSHOT] """, 0.378504495833,
                    ContentGenerator._generate_categories("music")),
            Content(""" Muse- The 2nd Law (Full Album) """, 0.421653535742,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - Nothing Else Matters (official video clip) """, 0.758775203589,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica Playlist """, 0.600174322912, ContentGenerator._generate_categories("music")),
            Content(""" Metallica-The Black Album-[Full Album] """, 0.588620693101,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - Nimes 2009 [Full Concert] HD.mp4 """, 0.619802332445,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica S&M 1999 Full Concert """, 0.576802284671,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - Enter Sandman [Official Music Video] """, 0.737146837426,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - Greatest Hits [Full Album] Vol..1 """, 0.641972632097,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - The Day That Never Comes [Official Music Video] """, 0.690831416278,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - Master Of Puppets (Live) """, 0.67526647853,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - One """, 0.786731621272, ContentGenerator._generate_categories("music")),
            Content(""" Metallica - Quebec Magnetic+Bonus - Full HD """, 0.458513347533,
                    ContentGenerator._generate_categories("music")),
            Content(""" Klasyczne albumy rocka - Metallica - The Black Album """, 0.482936810799,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica playlist """, 0.279098847509, ContentGenerator._generate_categories("music")),
            Content(""" Metallica - Freeze 'Em All: Live in Antarctica (FULL CONCERT) [HD] """, 0.598818514227,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - Fade To Black - Tłumaczenie """, 0.587370821249,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica Through The Never - zwiastun PL """, 0.54652817026,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica - The Unforgiven """, 0.743345718935, ContentGenerator._generate_categories("music")),
            Content(""" Metallica - ...And Justice for All (live Seattle, 1989) """, 0.572341544252,
                    ContentGenerator._generate_categories("music")),
            Content(""" Metallica: Am I Evil? (Live w/ The Big 4) [The Big 4: Live in Sofia, Bulgaria] """,
                    0.478356772838, ContentGenerator._generate_categories("music")),
            Content(""" Holy - Jesus Culture (Lyrics/Subtitles) (Best Worship Song for Jesus) """, 0.576441601196,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Life Of Jesus Christ New Full Movie │ Documentary 2013 │ """, 0.555925888793,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Best of Just For Laughs Gags - Best Jesus Pranks """, 0.663565089791,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Jesus Teaches a Samaritan Woman """, 0.539002849859,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Satanist Discovers That Jesus Christ Always Renders Satan Powerless! """, 0.561134725222,
                    ContentGenerator._generate_categories("religion")),
            Content(""" The Life Of Jesus Christ - LDS - Full Movie - Best Quality... """, 0.551867183644,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Archaeological Evidence for the Biblical tale of the Execution of Jesus [FULL DOCUMENTARY] """,
                    0.347304880509, ContentGenerator._generate_categories("religion")),
            Content(""" The Jesus Movie 1979 Full """, 0.643777449591,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Jews for Jesus """, 0.263245729218, ContentGenerator._generate_categories("religion")),
            Content(""" Jesus is not God? Zakir Naik answered on Jesus or Muhammad by David Wood and Sam Shamoun """,
                    0.406937205431, ContentGenerator._generate_categories("religion")),
            Content(""" Encounters With Jesus - Healing - Heaven - Hell - Angels - Miracles - Sid Roth """,
                    0.443678262499, ContentGenerator._generate_categories("religion")),
            Content(""" Jesus Will Survive - Jesus Christ! The Musical """, 0.701103398919,
                    ContentGenerator._generate_categories("religion")),
            Content(""" BBC - The Story of Jesus Part 2 """, 0.374004672405,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Jesús, el maestro de Nazaret: Primera Parte """, 0.467829070172,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Man Dies And Meets Jesus Christ In Heaven ! ( Near Death Experience ) """, 0.538387996697,
                    ContentGenerator._generate_categories("religion")),
            Content(""" 2014-2015 Blood Moons Jesus coming Perry Stone """, 0.500970154141,
                    ContentGenerator._generate_categories("religion")),
            Content(""" Jesus Gassed By Nazis In Stomach-Churning Ad [VIDEO] """, 0.48071221845,
                    ContentGenerator._generate_categories("religion")),
            Content(""" JESUS (English) """, 0.594017020625, ContentGenerator._generate_categories("religion")),
            Content(""" The Hidden Story of Jesus - Documentary """, 0.533818148619,
                    ContentGenerator._generate_categories("religion")),
            Content(""" 1 hora de música con Jesús Adrián Romero — Adoración Vol.1 [AudioHD] """, 0.714834752441,
                    ContentGenerator._generate_categories("religion")),
            Content(""" TOP 100 Goals in Football History ᴴᴰ """, 0.680602312464,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Ultimate Best Football Tricks & Skills """, 0.620764863721,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Comedy Football 2011 - (part 1-2) """, 0.707148043055,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Nike Football: Winner Stays. ft. Ronaldo, Neymar Jr., Rooney, Ibrahimović, Iniesta & more """,
                    0.734213247517, ContentGenerator._generate_categories("sport")),
            Content(""" K-State Football | Kaiden's Play """, 0.437318794991,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Vanier Football Challenge """, 0.404202392725, ContentGenerator._generate_categories("sport")),
            Content(""" ESPN Fan Hall of Famer Canaan Sandy Scores at Spring Football Game """, 0.364748077317,
                    ContentGenerator._generate_categories("sport")),
            Content(""" AMERICAN FOOTBALL TRAINING WITH WEIGHTS """, 0.387203966797,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Insane Football Skills Show 2014 | ep.3 """, 0.373647618203,
                    ContentGenerator._generate_categories("sport")),
            Content(
                """ Nike Football Commercial: Winner Stays. ft. Ronaldo, Neymar Jr., Rooney, Ibrahimović, Iniesta """,
                0.4030680664, ContentGenerator._generate_categories("sport")),
            Content(""" This Is Football 2012/13 1080p - Best Moments """, 0.58330169954,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Nike Football: Flyknit Mercurial Superfly IV """, 0.54448641829,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Nike Football Ronaldo Neymar Commercial REVIEW """, 0.426904570966,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Best Funny Football Moments 2013 | HD """, 0.536954423803,
                    ContentGenerator._generate_categories("sport")),
            Content(""" The BEST Street Football/Futsal/Freestyle Skills EVER!! ★ HD """, 0.650776576648,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Top 15 College Football Plays of 2013-14 (HD) """, 0.5565379047,
                    ContentGenerator._generate_categories("sport")),
            Content(
                """ Nike Football: Winner Stays. ft. Ronaldo, Neymar Jr., Rooney, Ibrahimović, Iniesta & more (2014) """,
                0.369381485389, ContentGenerator._generate_categories("sport")),
            Content(""" Funny Football moments 2013 - 2014 HD """, 0.531360572168,
                    ContentGenerator._generate_categories("sport")),
            Content(""" THE Football Free Kick Battle 2012 | freekickerz vs. Joltter | Vol.2 """, 0.659042115204,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Football's fight club - Part One - UK documentary """, 0.58110666912,
                    ContentGenerator._generate_categories("sport")),
            Content(""" Makeup Collection & Storage! Part 1 ♥ 화장품 컬랙션 & 보관대 """, 0.389987519602,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Makeup Collection & Storage! Part 2 ♥ 화장품 컬랙션 & 보관대 """, 0.377063112778,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Arabian Look (with subs) - Linda Hallberg Makeup Tutorials """, 0.398578561777,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" panacea81 """, 0.268124123738, ContentGenerator._generate_categories("fashion")),
            Content(""" Easy Fresh Face Makeup Tutorial """, 0.523517228042,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" My Milan Makeup Bag | ViviannaDoesMakeup """, 0.387783189149,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Prom Makeup Tutorial """, 0.667283756112, ContentGenerator._generate_categories("fashion")),
            Content(""" Spring Makeup Favourites | Hello October """, 0.383708315082,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" makeup Tutorial Scarlett Johansson inspired """, 0.466101717011,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Red Lips Makeup tutorial """, 0.434527568462, ContentGenerator._generate_categories("fashion")),
            Content(""" Picture Perfect for Prom: Colored Glamour ∙ Makeup Tutorial """, 0.470836990366,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Beyoncé Inspired MakeUp Tutorial / Evening MakeUp / Photo Shoot MakeUp """, 0.533020672383,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" The Perfect Spring Look: Makeup, Hair, & Outfit! """, 0.418258582546,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Prom Makeup Tutorial & Hair Tutorial | TheMakeupChair """, 0.467110801781,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Kim Kardashian ♡ Hair & Makeup | Glamorous Warm Neutral Eyes & Red Lip! """, 0.520333754819,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Big Sephora Haul ♥ Makeup, Skincare, and More! """, 0.513818897709,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Not My Arms Makeup Challenge w/ my Husband "Night on the Town Look" """, 0.485915631744,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Ep 6: Yhomira | Giving Back Glam with ||Superwoman|| // I love makeup. """, 0.402950552543,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Kim Kardashian Inspired Makeup Tutorial New """, 0.451658825281,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" Pony's Beauty Diary - Play 101 Pencil Makeup (청초/코랄/레트로 메이크업) """, 0.504802206765,
                    ContentGenerator._generate_categories("fashion")),
            Content(""" MinutePhysics """, 0.210037054512, ContentGenerator._generate_categories("history")),
            Content(""" 100 Greatest Discoveries - Physics """, 0.513480163423,
                    ContentGenerator._generate_categories("history")),
            Content(""" For the Love of Physics (May 16, 2011) """, 0.599351514588,
                    ContentGenerator._generate_categories("history")),
            Content(""" Introduction to Physics: Educational Film """, 0.45562421779,
                    ContentGenerator._generate_categories("history")),
            Content(""" Quantum Physics &amp; Microscopic Universe [Full Documentary] """, 0.364904263409,
                    ContentGenerator._generate_categories("history")),
            Content(""" A Crash Course In Particle Physics (1 of 2) """, 0.5425760764,
                    ContentGenerator._generate_categories("history")),
            Content(""" Allan Adams: The discovery that could rewrite physics """, 0.495264232648,
                    ContentGenerator._generate_categories("history")),
            Content(""" Common Physics Misconceptions """, 0.638863911625,
                    ContentGenerator._generate_categories("history")),
            Content(""" COLD HARD SCIENCE. The Controversial Physics of Curling - Smarter Every Day 111 """,
                    0.555869417379, ContentGenerator._generate_categories("history")),
            Content(
                """ iTTV SPM Form 4 Physics Chapter 2 Force And Motion (Linear Motion) -Tuition/Lesson/Exam/Tips """,
                0.459658610069, ContentGenerator._generate_categories("history")),
            Content(""" Fay Dowker - Spacetime Atoms and the Unity of Physics (Perimeter Public Lecture) """,
                    0.486148661792, ContentGenerator._generate_categories("history")),
            Content(""" 0rbitalis - 2D Gravity Physics Puzzle Game on Steam Early Access """, 0.420115122766,
                    ContentGenerator._generate_categories("history")),
            Content(""" Introduction to Particle Physics Part 1/4 """, 0.444496552335,
                    ContentGenerator._generate_categories("history")),
            Content(""" Physics. """, 0.264345267649, ContentGenerator._generate_categories("history")),
            Content(""" AN  AWESOME  FUTURE!  Michio Kaku  - Physics of the Future """, 0.361384182188,
                    ContentGenerator._generate_categories("history")),
            Content(""" COLD HARD SCIENCE.The Physics of Skating on Ice (With SlowMo) - Smarter Every Day 110 """,
                    0.597877332828, ContentGenerator._generate_categories("history")),
            Content(""" Particles, Fields and The Future of Physics - A Lecture by Sean Carroll """, 0.480187685376,
                    ContentGenerator._generate_categories("history")),
            Content(""" Quantum Physics Debunks Materialism """, 0.48696892485,
                    ContentGenerator._generate_categories("history")),
            Content(""" Stanford Professor Andrei Linde celebrates physics breakthrough """, 0.645255321642,
                    ContentGenerator._generate_categories("history")),
            Content(
                """ Michio Kaku ★ Quantum Physics God And Science Multiverse Theory Quantum Mechanics - Universe """,
                0.396004245573, ContentGenerator._generate_categories("history")),
            Content(""" FilmWebTV """, 0.285733249643, ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb rozmawia z Januszem Gajosem """, 0.452972543061,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb rozmawia z Wojciechem Smarzowskim """, 0.31535099893,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Hobbit  Pustkowie Smauga   zwiastun Filmweb """, 0.258658730467,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb na premierze "Miłości" """, 0.335926616461,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb na premierze "W ukryciu" """, 0.316554107672,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Aplikacja Filmweb na Samsung Smart TV """, 0.340329214516,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb rozmawia z twórcami "Czekając na sobotę" """, 0.560513366538,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Bezstronnie Polecamy Extra: Filmweb """, 0.328103336725,
                    ContentGenerator._generate_categories("movies")),
            Content(""" XBMC - Ustawienie scrapera FilmWeb """, 0.349234125325,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb rozmawia z Billem Nighym """, 0.268214507637,
                    ContentGenerator._generate_categories("movies")),
            Content(""" "Filmweb - 10 to za mało" - film 2 """, 0.350392680419,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb Offline 2009 """, 0.460370718267, ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb - recenzja aplikacji na Androida i IOS """, 0.267760695272,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Percy Jackson  Morze potworów (polski dubbing)   Filmweb """, 0.404151111296,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb Offline 2011 """, 0.342226145081, ContentGenerator._generate_categories("movies")),
            Content(""" Cleanskin 2012 Asa | Cleanskin Filmweb | Fresh Clean Skin """, 0.151851393988,
                    ContentGenerator._generate_categories("movies")),
            Content(""" MooViDb - Filmweb API w akcji """, 0.238381536598,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb.pl od kuchni cz.2 """, 0.244870631991, ContentGenerator._generate_categories("movies")),
            Content(""" Filmweb rozmawia z gwiazdą "Życia Pi" - Suraj Sharmą """, 0.353781909507,
                    ContentGenerator._generate_categories("movies")),
            Content(""" Documentary World War 2 II in Colour The Second World War color """, 0.617248908911,
                    ContentGenerator._generate_categories("history")),
            Content(""" Secret Stories Of World War 2 - National Geographic Documentary """, 0.604931572794,
                    ContentGenerator._generate_categories("history")),
            Content(""" World War Two: Germany invades Russia 1941 """, 0.569919230621,
                    ContentGenerator._generate_categories("history")),
            Content(""" World War II Blitzkrieg """, 0.405480450022, ContentGenerator._generate_categories("history")),
            Content(""" Tankies: Tank Heroes of World War II, Episode 1 of 2 """, 0.589296899229,
                    ContentGenerator._generate_categories("history")),
            Content(""" World War 2 1945 Documentory - Hitler in Colour - Real Footage - by roothmens """,
                    0.437845241148, ContentGenerator._generate_categories("history")),
            Content(""" Inside World War II """, 0.564815892025, ContentGenerator._generate_categories("history")),
            Content(""" World War Two: Soviet Union 1943 """, 0.582319178072,
                    ContentGenerator._generate_categories("history")),
            Content(""" World War II: Crash Course World History #38 """, 0.623314008943,
                    ContentGenerator._generate_categories("history")),
            Content(
                """ WW2 - Japanese Invasion of China | The Second Sino-Japanese War: 1937-45 | SHOCKING WWII Documentary """,
                0.534186366056, ContentGenerator._generate_categories("history")),
            Content(""" World War II in Europe: Every Day """, 0.633461396822,
                    ContentGenerator._generate_categories("history")),
            Content(""" World War Two: The End 1945 """, 0.558065816169,
                    ContentGenerator._generate_categories("history")),
            Content(""" World War Two Documentary - 132 Minutes """, 0.566512770004,
                    ContentGenerator._generate_categories("history")),
            Content(""" Victor Davis Hanson - World War II Leadership """, 0.422659990521,
                    ContentGenerator._generate_categories("history")),
            Content(""" World War II in Europe and the Pacific: Every Day """, 0.532386442584,
                    ContentGenerator._generate_categories("history")),
            Content(""" Brutal Combat in Second World War (graphic) """, 0.589658242963,
                    ContentGenerator._generate_categories("history")),
            Content(""" World History - Causes of World War II """, 0.446622979171,
                    ContentGenerator._generate_categories("history")),
            Content(""" Second World War 'The True Story' untold """, 0.318469143082,
                    ContentGenerator._generate_categories("history")),
            Content(""" Antony Beevor, Author, "The Second World War" """, 0.387349498226,
                    ContentGenerator._generate_categories("history")),
            Content(""" Historical maps 1 - World War II """, 0.524741101875,
                    ContentGenerator._generate_categories("history")),
            Content(""" How to Save Money by Eliminating 10 Things You Don't Need """, 0.556186073475,
                    ContentGenerator._generate_categories("money")),
            Content(""" 10 TIPS ON HOW TO SAVE MONEY $$ """, 0.482994669594,
                    ContentGenerator._generate_categories("money")),
            Content(""" Suze Orman: To really save money, do this... """, 0.512936114735,
                    ContentGenerator._generate_categories("money")),
            Content(""" The Absolute Best Ways To Save Money """, 0.467137651518,
                    ContentGenerator._generate_categories("money")),
            Content(""" Saving Money: How to Make It Feel Good """, 0.393731724776,
                    ContentGenerator._generate_categories("money")),
            Content(""" How to Start Saving Money """, 0.30817072701, ContentGenerator._generate_categories("money")),
            Content(""" Saving Money - How To Save Money (Money Management) """, 0.375807882225,
                    ContentGenerator._generate_categories("money")),
            Content(""" Tips for Saving Money on Water Heating """, 0.430734625537,
                    ContentGenerator._generate_categories("money")),
            Content(""" Frugal Living, practical tips for saving money - Lynnae McCoy - theDove.us """, 0.47424973222,
                    ContentGenerator._generate_categories("money")),
            Content(""" Super savers share secrets to saving money and building bank """, 0.44126956916,
                    ContentGenerator._generate_categories("money")),
            Content(""" How To Save A Lot Of Money Every Year By Saving Change & Dollar Bills """, 0.434163233578,
                    ContentGenerator._generate_categories("money")),
            Content(""" Smart ways to save money """, 0.40652808711, ContentGenerator._generate_categories("money")),
            Content(""" MONEY SAVING TIPS!!! """, 0.389376176206, ContentGenerator._generate_categories("money")),
            Content(""" Keith Chen: Could your language affect your ability to save money? """, 0.503376140879,
                    ContentGenerator._generate_categories("money")),
            Content(""" Saving Money for College """, 0.474722530868, ContentGenerator._generate_categories("money")),
            Content(""" Saving Money """, 0.296988164375, ContentGenerator._generate_categories("money")),
            Content(""" 10 Easy Ways To Save Money Every Month """, 0.501684538275,
                    ContentGenerator._generate_categories("money")),
            Content(""" Personal Finance-Saving Money, Investing, and Retirement Planning Part 1 """, 0.388195497134,
                    ContentGenerator._generate_categories("money")),
            Content(""" (Cheap Comcast Service Trick) Saving Money On Your Comcast Internet and Cable Bill """,
                    0.464520605086, ContentGenerator._generate_categories("money")),
            Content(""" DIS Unplugged - Saving Money On Your DCL Vacation - 04/01/14 """, 0.342012084809,
                    ContentGenerator._generate_categories("money")),
            Content(""" ja putin pl """, 0.537773232098, ContentGenerator._generate_categories("politics")),
            Content(""" Rzeźnik Putin: Morderstwa i Zamachy FSB / Rebellion: The Litvinenko Case [Lektor PL] """,
                    0.556638327566, ContentGenerator._generate_categories("politics")),
            Content(
                """ UFO Sightings Edward Snowden Leaks Information To President Putin? Incredible UFO Videos 2014 """,
                0.351600623039, ContentGenerator._generate_categories("politics")),
            Content(""" Putin: Internet began as CIA project """, 0.438390508698,
                    ContentGenerator._generate_categories("politics")),
            Content(""" The Trap! Obama and Putin Would Save One Another, But Would Watch Us All Die! """,
                    0.407158747051, ContentGenerator._generate_categories("politics")),
            Content(""" Putin - Największa Zaraza tego Świata """, 0.468369529283,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Putin Hangs Phone Up In Obama's Face """, 0.320844135644,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Obama: I'd Absolutely Save Putin From Drowning """, 0.366294661433,
                    ContentGenerator._generate_categories("politics")),
            Content(""" BREAKING! Putin Halts All Talks With White House; WAR DRUMS LOUD ENOUGH YET """, 0.323248786635,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Obama: Putin Views World Through Cold War Prism """, 0.344591541395,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Putin on the future Russia Ukraine relationships """, 0.388184096832,
                    ContentGenerator._generate_categories("politics")),
            Content(""" PUTIN ORDERS Air defence exercises in Russia warning to obama """, 0.374601110775,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Putin & Obama Go On "Dr. Phil" Show """, 0.546491111811,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Czy Putin zatrzyma sie na Krymie - Max Kolonko Mówi Jak Jest """, 0.554965666561,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Putin in der Zwickmühle? Dirk Müller Tagesausblick 25.04.2014 - die Bananenrepublik """,
                    0.421719431801, ContentGenerator._generate_categories("politics")),
            Content(""" Putin warns of "consequences" if Ukraine military continues crackdown """, 0.411055604276,
                    ContentGenerator._generate_categories("politics")),
            Content(""" RUSSIA-PUTIN / UKRAINE RUMOUR OF WORLD WAR 3 | See DESCRIPTION """, 0.309447112864,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Putin: Jeszcze Polska nie zginęła 20.12.2012 """, 0.438962672393,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Putin: How was the decision about Crimea made """, 0.408834875229,
                    ContentGenerator._generate_categories("politics")),
            Content(""" Obama: I would absolutely save Putin from drowning """, 0.454046712558,
                    ContentGenerator._generate_categories("politics")),
        ]

